#!/usr/bin/env bash

say() {
  # echo
  # echo
  echo "======== $1 ========="
  # echo
}

note() {
  echo "-----------> $1"
}

test() {
  if ([ "$1" = "all" ]); then
    note testing everything
    yarn test
    slang hello.sl
  else
    note "testing just (jesting) $1"
    yarn test $1
  fi
}

cli() {
    note "launching cli"
    slang
}

say "slang dev task runner"
if [ "$1" = "c" ]; then
  cli
else
  test $1 $2
fi

