#!/usr/bin/env bash

say() {
  echo
  echo
  echo "======== $1 ========="
  echo
}

note() {
  echo "-----------> $1"
}

test() {
  note testing
  yarn test
}

cli() {
    note "launching cli"
    slang
}

say "slang dev task runner"
if [ "$1" = "c" ]; then
  cli
else
  test
fi

