#!/usr/bin/env bash

say() {
  echo "$1"
}

note() {
  echo "  -> $1"
}

test() {
  if ([ "$1" = "all" ]); then
    note "testing everything"
    yarn --silent test
    slang hello.sl
  else
    # note "testing $1"
    yarn test $1
  fi
}

cli() {
    note "launching cli"
    slang
}

# say "slang dev task runner"
if [ "$1" = "c" ]; then
  cli
else
  test $1 $2
fi

